// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKt18L9-460DXX6VMO1pW5UOpBMtgVpuQ',
    appId: '1:781227808077:web:f590ab14ffa201c3379304',
    messagingSenderId: '781227808077',
    projectId: 'fruit-h',
    authDomain: 'fruit-h.firebaseapp.com',
    storageBucket: 'fruit-h.appspot.com',
    measurementId: 'G-CGHD9X84H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvi14N23hVOE-spH5VlC8tcVl9Y1InY98',
    appId: '1:781227808077:android:53030d78f1f363e1379304',
    messagingSenderId: '781227808077',
    projectId: 'fruit-h',
    storageBucket: 'fruit-h.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCszsQ_YKlrEN-WoGtWM4d0ARvCuO7o2bo',
    appId: '1:781227808077:ios:0ebd13d3ebb90d81379304',
    messagingSenderId: '781227808077',
    projectId: 'fruit-h',
    storageBucket: 'fruit-h.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCszsQ_YKlrEN-WoGtWM4d0ARvCuO7o2bo',
    appId: '1:781227808077:ios:0ebd13d3ebb90d81379304',
    messagingSenderId: '781227808077',
    projectId: 'fruit-h',
    storageBucket: 'fruit-h.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKt18L9-460DXX6VMO1pW5UOpBMtgVpuQ',
    appId: '1:781227808077:web:d7827ee83fd7a9ad379304',
    messagingSenderId: '781227808077',
    projectId: 'fruit-h',
    authDomain: 'fruit-h.firebaseapp.com',
    storageBucket: 'fruit-h.appspot.com',
    measurementId: 'G-6T97X42Z8C',
  );
}
